import { Geist, Geist_Mono, Tajawal } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import Providers from "./theme";
import Sidebar from "./sidebar.js";
import DataContext from "./context/Context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["arabic" , "latin"],
//   weight: ["400" , "600" , "700"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--font-tajawal",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${tajawal.className}`}>
        <Providers>
          <DataContext>
            <Sidebar />
            {children}
          </DataContext>
        </Providers>
      </body>
    </html>
  );
}
