import { Geist, Geist_Mono, Tajawal } from "next/font/google";
import "./globals.css";
import AnchorTemporaryDrawer from "../app/Sidebar";
import Link from "next/link";
import Providers from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["arabic" , "latin"],
//   weight: ["400" , "600" , "700"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--font-tajawal",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${tajawal.className}  main-layout `}>
        <Providers>
          <AnchorTemporaryDrawer />
          {children}
        </Providers>
      </body>
    </html>
  );
}
