import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex justify-center items-center gap-5 p-10 bg-red-400 text-4xl">
          <Link href={"/"}>Home</Link>
          <Link href={"/posts"}>Posts</Link>
          <Link href={"/articles"}>Articels</Link>
        </nav>

        {children}
        <footer className="flex justify-center items-center gap-5 p-10 bg-red-400 text-8xl">
          Baker Hallak
        </footer>
      </body>
    </html>
  );
}
